home:
    path: /
    controller: App\Controller\HomeController::home

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_login:
    path: /login
    controller: App\Controller\LoginController::login

app_logout:
    path: /logout
    controller: App\Controller\LoginController:logout

app_admin:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index